#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Dungeons_and_Dragons_5e_Dice_Roller.Resource", IsApplication=true)]

namespace Dungeons_and_Dragons_5e_Dice_Roller
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int background_color = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int button_color = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int d10_0 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int d10_00 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int d10_1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int d10_10 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int d10_2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int d10_20 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int d10_3 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int d10_30 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int d10_4 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int d10_40 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int d10_5 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int d10_50 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int d10_6 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int d10_60 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int d10_7 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int d10_70 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int d10_8 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int d10_80 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int d10_9 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int d10_90 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int d20_1 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int d20_10 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int d20_11 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int d20_12 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int d20_13 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int d20_14 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int d20_15 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int d20_16 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int d20_17 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int d20_18 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int d20_19 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int d20_2 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int d20_20 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int d20_3 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int d20_4 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int d20_5 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int d20_6 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int d20_7 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int d20_8 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int d20_9 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int d20_X = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int damage = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int DownArrow = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Icon = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int percentile = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int UpArrow = 2130837549;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060012
			public const int ActivitySwitchBox = 2131099666;
			
			// aapt resource value: 0x7f060000
			public const int AdvantageCheckBox = 2131099648;
			
			// aapt resource value: 0x7f060020
			public const int AmountDownButton = 2131099680;
			
			// aapt resource value: 0x7f06001d
			public const int AmountText = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int AmountUpButton = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int AmountValueText = 2131099679;
			
			// aapt resource value: 0x7f060022
			public const int D20ImageButton = 2131099682;
			
			// aapt resource value: 0x7f060013
			public const int DamageImageButton = 2131099667;
			
			// aapt resource value: 0x7f060021
			public const int DieRollText = 2131099681;
			
			// aapt resource value: 0x7f060015
			public const int DieSelectRadioGroup = 2131099669;
			
			// aapt resource value: 0x7f060001
			public const int DisadvantageCheckBox = 2131099649;
			
			// aapt resource value: 0x7f06000f
			public const int LeftXImage = 2131099663;
			
			// aapt resource value: 0x7f06000b
			public const int ModifierDownButton = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int ModifierText = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int ModifierUpButton = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int ModifierValueText = 2131099658;
			
			// aapt resource value: 0x7f060026
			public const int OnesDieImage = 2131099686;
			
			// aapt resource value: 0x7f060023
			public const int PercentileDiceBox = 2131099683;
			
			// aapt resource value: 0x7f060014
			public const int PercentileImageButton = 2131099668;
			
			// aapt resource value: 0x7f060024
			public const int PercentileRollText = 2131099684;
			
			// aapt resource value: 0x7f060010
			public const int RightXImage = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int RollButton = 2131099665;
			
			// aapt resource value: 0x7f060002
			public const int SetupBox = 2131099650;
			
			// aapt resource value: 0x7f060025
			public const int TensDieImage = 2131099685;
			
			// aapt resource value: 0x7f06001c
			public const int TotalRollText = 2131099676;
			
			// aapt resource value: 0x7f060019
			public const int d10RadioButton = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int d12RadioButton = 2131099674;
			
			// aapt resource value: 0x7f060003
			public const int d20DiceBox = 2131099651;
			
			// aapt resource value: 0x7f06000d
			public const int d20LeftImage = 2131099661;
			
			// aapt resource value: 0x7f06001b
			public const int d20RadioButton = 2131099675;
			
			// aapt resource value: 0x7f06000e
			public const int d20RightImage = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int d20RollText = 2131099660;
			
			// aapt resource value: 0x7f060016
			public const int d4RadioButton = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int d6RadioButton = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int d8RadioButton = 2131099672;
			
			// aapt resource value: 0x7f060004
			public const int tableLayout1 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int tableRow1 = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int tableRow2 = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int tableRow3 = 2131099657;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int d20 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DamageDice = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Percentile = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
